Containerize project : configure dockerfile and compose files
wavetermdev/waveterm pull request #767
Opened 2024-08-25 18:53 UTC by sujal-goswami

resolve #740 

For user to build this project using docker they need to fulfil the prerequisites:

## Prerequistes
-  Docker Desktop or docker should be installed
-  WSL - Windows Subsystem for Linux  (only for windows users)
- should have `X server` installed in host machine
if not have then can download from command `sudo apt-get install x11-xserver-utils`.
to check its correct installation run `xhost` this should give output as 
```
access control disabled, clients can connect from any host
LOCAL:
SI:localuser:wslg
```
## demo image
<img width="964" alt="wave" src="https://github.com/user-attachments/assets/5ff1725a-21e2-4f9c-b6ce-bbee675dc70d">

## References
[https://github.com/cypress-io/cypress-documentation/issues/5816](https://github.com/cypress-io/cypress-documentation/issues/5816)
[--no-sandbox error](https://ask.replit.com/t/get-error-by-command-chromium-browser-no-sandbox/14514/2)

2024-08-25 18:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wavetermdev/waveterm?pullRequest=767) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wavetermdev/waveterm?pullRequest=767) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wavetermdev/waveterm?pullRequest=767) it.</sub>

2024-08-25 20:48 UTC, esimkowitz commented
Thank you for setting this up! Since this is for a dev container, I think the .dockerignore doesn't need to be as restrictive, since the developer may care about the .md, config, and Yarn files. Otherwise it looks good to me!

2024-08-26 03:02 UTC, esimkowitz requested changes
Based on your issue, I assumed you meant to create a docker container for development purposes, usually for something like this you would want to add the VSCode tooling for Dev Containers and leave the repo data inside the final container. (see [Developing inside a Container](https://code.visualstudio.com/docs/devcontainers/containers)

I'm not sure I see a point to just running our app in a container, since it won't have access to the rest of your system, which kind of defeats the purpose of a terminal app.

2024-08-26 20:50 UTC, esimkowitz commented
Could you verify that this complies with the guidelines for the dev containers in the guide I linked ([Developing inside a Container](https://code.visualstudio.com/docs/devcontainers/containers))? This one may also be helpful: [Create a development container](https://code.visualstudio.com/docs/devcontainers/create-dev-container#_path-to-creating-a-dev-container). I think you can skip setting a CMD to start on container run, since this is not necessary for developing inside a container. Also I realize the suggested changes I made left a bunch of new lines, could you clean those up?

2024-08-27 04:19 UTC, sujal-goswami commented
Sure !

2024-08-27 18:53 UTC, sujal-goswami commented
now I think it is good to go; now, the user can use the VS Code dev container feature for seamless development in the container with pre-install go , eslint and prettier extensions in it.

2024-08-28 19:31 UTC, esimkowitz commented
I don't think you need to build the app at all in the dockerfile, since it's fast enough. Also, because webpack-watch is blocking, the dockerfile never completes. I moved this to the "postStartCommand" in devcontainer.json, but I'm still unable to launch the app, as it's complaining about DBus not being started. I tried moving the `service dbus start` command to the postStartCommand too, but it's still not working. What host OS are you using to test this? I'm on macOS 14.

I'm concerned that if the devcontainer isn't reliable on all platforms or requires additional hoops to get working, it won't be that much better than just installing the deps directly. Aside from scripthaus, we don't have any crazy dependencies. We're also in the process of a pretty large rearchitecting and we're removing the scripthaus dependency as part of this, so our dependency story will get a lot simpler.

2024-08-29 11:01 UTC, sujal-goswami commented
I don't think the host OS is the issue here. It's more likely an issue with the dbus service. I encountered a similar dbus error during my testing but resolved it by running `service dbus start` on the machine. You can refer to this [link](https://ask.replit.com/t/get-error-by-command-chromium-browser-no-sandbox/14514/2) for more details. By the way, I'm using Windows as the host OS, so it's odd if the OS is indeed the problem. The rearchitecting plan sounds great! Simplifying the dependencies will definitely streamline the process.

2024-11-19 21:40 UTC, klmcwhirter commented
FWIW, I did something similar as this PR - but, my goal was to build waveterm in a container - not run it in the container.

I purposely do not install multiple tool chains, project specific dependencies, etc. on localhost.

FYI, I am running on Fedora 41 and typically use VS Code (although I have been using `emacs -nw` again lately.

I concur that .devcontainer might be of dubious value, and there are several missing extensions that I typically use for web dev (vscode-tailwindcss, etc.). So I would probably just create my own.

In my case, I chose fedora:41 as the base OCI image because I wanted to be sure the resulting binary would run on my system.

That is not an issue when running in a container. If I was looking for containerization, I would prefer flatpak as an execution env because it is a more natural fit.

I suspect there may be a number of personal preferences out there.

But agree with @esimkowitz - thanks for putting in the effort. I am sure there are devs out there who can benefit.

2024-11-19 21:44 UTC, klmcwhirter commented on Dockerfile
> +RUN git clone https://github.com/scripthaus-dev/scripthaus.git
Someone probably already has commented on this ...

But is this the github project you really intended to merge? note scripthaus-dev ...

2024-12-23 18:00 UTC, esimkowitz commented
Closing this PR for now, sorry we couldn't get it merged

2024-12-23 18:00 UTC, closed without merging